### ISSUE TITLE
how to set backgourd-color transparent?

### ISSUE THREAD

**Issue by cwwjsyc** [federico-moretti/canvas-free-drawing#13]
how to set backgourd-color transparent?

**Comment by federico-moretti** [comment]
Did you try to do something like `cfd.setBackground([0,0,0,0])` ?

**Comment by federico-moretti** [comment]
Ok, I did try it myself and it works fine. If you want to set it as default, you have to use `cfd.setBackground([0,0,0,0], true)` or set the background during the init.

**Comment by cwwjsyc** [comment]
Learning ！ Thanks。
