### ISSUE TITLE
Issue on Touch Screen

### ISSUE THREAD

**Issue by tettusud** [federico-moretti/canvas-free-drawing#14]
thank you for wonderful work on such a light weight and amazing plugin,
I am currently facing issue on touch screen, there is a gap between the pointer and actual point where it is drawing.
 I am able to reproduce it by cloning your repo and running your example ( a simple http-server locally).
Where as the one on this website works fine https://www.federicomoretti.dev/canvas-free-drawing. Not sure what is that am missing.

Once again I appreciate your time

**Comment by tettusud** [comment]
My mistake ,looks like some other scripts is causing that .Thank you.

**Comment by federico-moretti** [comment]
Happy to know everything works fine and thank you for using/enjoying my library!
