### ISSUE TITLE
Allow colors with alpha channel.

### ISSUE THREAD

**Issue by zobier** [federico-moretti/canvas-free-drawing#6]
I see it is just ignoring alpha channel: https://github.com/Ikos9/canvas-free-drawing/blame/master/src/index.ts#L464

Is there a reason for this?

**Comment by Ikos9** [comment]
Not really, it's something that I didn't need and has never been requested. It's not a huge change, I may implement it in a few days or if you wanna do a PR it's welcome.

**Comment by federico-moretti** [comment]
Fixed in v2.1.0
