### ISSUE TITLE
Positioned elements causes issues

### ISSUE THREAD

**Issue by cttobin** [federico-moretti/canvas-free-drawing#7]
Nice little library you have here. I have no idea if you're still maintaining it, but relative/absolute/fixed positioned elements cause mouse events to have the wrong coordinates. [See here for an example](https://jsfiddle.net/hf9bcjrz/).

I think it might be related to how you use `pageX` and `pageY` with `offsetLeft` and `offsetTop` in the mouse events.

**Comment by federico-moretti** [comment]
I'll try to fix it in the next few days, thanks for the report!
Also thank you for using it and the compliments!

**Comment by jordoreed** [comment]
@federico-moretti love this simple library. do you have any plans to push this fix out to npm anytime soon? if not i can just pull the repo directly. thanks!

**Comment by federico-moretti** [comment]
Fixed in v2.1.0

**Comment by jordoreed** [comment]
@federico-moretti  thanks! :)
